
source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'pagy', '~>3.7.0'

gem 'rails', '~> 5.2.3'
gem 'sqlite3'
gem 'puma', '~> 3.11'

gem 'bootstrap', '~> 4.3.1'
gem 'jquery-rails', '~> 4.3.5'
gem 'popper_js', '~> 1.14.5'
gem 'font-awesome-sass', '~> 5.9.0'
gem 'sassc', '~> 2.2.1'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks', '~> 5'

#gem 'jbuilder', '~> 2.5'

#gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.5'

group :development do
  gem 'web-console', '>= 3.3.0'
    gem 'faker', '~>2.7.0'
end

