
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '~> 6.0'
gem 'sqlite3', '~> 1.4'
gem 'pg', '~> 1.1'

gem 'puma', '~> 4.1'
gem 'sass-rails', '~> 6'
gem 'webpacker', '~> 4.2'
gem 'turbolinks', '~> 5'

gem 'jbuilder', '~> 2.7'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '~> 1.4'
gem 'uglifier', '~> 4.2'

gem 'dalli', '~> 2.7'

group :development do
  gem 'web-console', '~> 4.0'
  gem 'spring', '~> 2.1'
  gem 'faker', '~> 2.7'
end

##gem 'bootstrap', '~> 4.3.1'
##gem 'jquery-rails', '~> 4.3.5'
##gem 'popper_js', '~> 1.14.5'
##gem 'font-awesome-sass', '~> 5.9.0'
##gem 'font_awesome5_rails'

gem 'pagy', '~>3.7'

